### ISSUE TITLE
provider?

### ISSUE THREAD

**Issue by lorddrachenblut** [pandrew/docker-metasploit#2]
I've only played with docker a little but I believe there is a provider label that can be added to a Dockerfile that  explicitly says what base os to use.  This is really useful for people who run a Dockerfile on a different host os.  Is this something you could add to help improve the portability of your Dockerfile?

**Comment by pandrew** [comment]
There´s no such label to my knowledge but please pinpoint me and i can see if i can add it. The host os needs to be able to run the docker in daemon mode, if it is able to run it it can also build to dockerfile. Host os should not matter.
